### ISSUE TITLE
你好，想请教一下图片显示的问题

### ISSUE THREAD

**Issue by lsl-ctrl** [codingZhangxin/OnlineSchoolShop#13]
你好，前端页面图片显示不出来，应该是路径不对。但是我看代码没有理解到，数据库存放的是图片路径，不知道具体图片存放逻辑是什么。另外，如果方便，希望可以提供一下需求分析文档参考一下，便于理清整个项目逻辑。感谢

**Comment by codingZhangxin** [comment]
呃 你应该是想作为毕业设计吧。多看看源码，图片没显示出来是 数据库里面存的路径不对
